

# 生产环境

mybatis-plus:
    # SQL语句打印
    configuration:
        log-impl: org.apache.ibatis.logging.stdout.StdOutImpl
    # 逻辑删除
    global-config:
        db-config:
            logic-delete-value: 1
            logic-not-delete-value: 0
    # 映射文件相关
    mapper-locations: classpath*:bml/mapper/xml/*.xml
    type-aliases-package: bml.mapper

server:
    tomcat:
        uri-encoding: UTF-8

spring:
    # Druid数据库相关
    datasource:
        driver-class-name: com.mysql.cj.jdbc.Driver
        type: com.alibaba.druid.pool.DruidDataSource
        url: jdbc:mysql://192.168.65.130:3306/docker?useUnicode=true&characterEncoding=utf8&serverTimezone=GMT%2B8&useSSL=false
        username: root
        password: 123456
        druid:
            connect-properties: druid.stat.mergeSql=true;druid.stat.slowSqlMillis=5000
            filters: stat,wall
            initial-size: 5
            max-active: 20
            max-pool-prepared-statement-per-connection-size: 20
            max-wait: 60000
            min-evictable-idle-time-millis: 300000
            min-idle: 5
            pool-prepared-statements: true
            test-on-borrow: false
            test-on-return: false
            test-while-idle: true
            time-between-eviction-runs-millis: 60000
            valid-connection-checker-class-name: com.alibaba.druid.pool.vendor.MSSQLValidConnectionChecker
            validation-query: SELECT 1 FROM DUAL
    # 页面编码
    http:
        encoding:
            charset: UTF-8
            enabled: true
            force: true
    mvc:
        # 设置RestFul风格，好像已默认关闭
        hiddenmethod:
            filter:
                enabled: true
        # 静态资源文件
        static-path-pattern: /static/**
    thymeleaf:
        cache: false
        encoding: UTF-8
        mode: HTML
        servlet:
            content-type: text/html


    ### redis相关配置
    redis:
        host: 192.168.65.130
        port: 6379
        timeout: 5000
        database: 3
        lettuce:
            pool:
                # 最大空闲连接数（默认为8，负数表示无限）
                max-idle: 8
                # 最小空闲连接数（默认为0，该值只有为正数才生效）
                min-idle: 0
                # 最大可用连接数（默认为8 负数表示无限）
                max-active: 8
                # 从连接池中获取连接最大等待时间（默认为-1，单位为毫秒，负数表示无限）
                max-wait: -1

    cache:
        type: redis
